#!/bin/sh

echo 'Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "no"
        Option "XkbModel" "pc105"
        Option "XkbOptions" "terminate:ctrl_alt_bksp"
        Option "AutoRepeat" "280 30"
EndSection'>/etc/X11/xorg.conf.d/10-keyboard.conf

exit 0
